// Generated by ReScript, PLEASE EDIT WITH CARE


function valueOfDevice(value) {
  if (value === "md") {
    return "960px";
  } else if (value === "sm") {
    return "600px";
  } else if (value === "xl") {
    return "1920px";
  } else if (value === "xs") {
    return "470px";
  } else if (value === "xxs") {
    return "0px";
  } else {
    return "1280px";
  }
}

function greaterThan(current, device, styles) {
  return "\n  " + current + "\n  @media (min-width: " + valueOfDevice(device) + ") {\n    " + styles + "\n  }\n  ";
}

var Raw = {
  greaterThan: greaterThan
};

export {
  valueOfDevice ,
  Raw ,
  
}
/* No side effect */
