// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";

function includeStyle(param) {
  CssJs.$$global("html, body, #root", [
        CssJs.padding(CssJs.zero),
        CssJs.margin(CssJs.zero)
      ]);
  return CssJs.$$global("html", [CssJs.fontSize(CssJs.px(10))]);
}

export {
  includeStyle ,
  
}
/* CssJs Not a pure module */
