// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function s(prim) {
  return prim;
}

function map(elements, fn) {
  return Belt_Array.mapWithIndex(elements, (function (key, element) {
                return Curry._2(fn, element, String(key));
              }));
}

export {
  s ,
  map ,
  
}
/* No side effect */
