// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";

var Colors = {
  blue: "477BFF",
  white: "fff"
};

var small = CssJs.px(6);

var medium = CssJs.px(12);

var large = CssJs.px(16);

var Radius = {
  small: small,
  medium: medium,
  large: large
};

var fontFamily = {
  NAME: "custom",
  VAL: "'DM Sans', sans-serif"
};

export {
  Colors ,
  Radius ,
  fontFamily ,
  
}
/* small Not a pure module */
