// Generated by ReScript, PLEASE EDIT WITH CARE


var Colors = {
  blue: "#477BFF",
  white: "#fff",
  gray1: "#A6AABE",
  gray2: "#AEB3C9",
  black: "#14103D",
  lightBlue1: "#E2EAFF",
  blueGradient: "linear-gradient(180.0deg, 0 #477BFF, 100% #306AFF)"
};

var Radius = {
  small: "6px",
  medium: "12px",
  large: "16px"
};

function make(value) {
  return (value * 0.6).toString() + "rem";
}

var Spacing = {
  make: make
};

var fontFamily = {
  NAME: "custom",
  VAL: "'DM Sans', sans-serif"
};

export {
  Colors ,
  Radius ,
  Spacing ,
  fontFamily ,
  
}
/* No side effect */
