// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Render from "../../lib/Render.bs.js";

require("./button.css");

function Button(Props) {
  return React.createElement("button", undefined, Render.s("Sign in"));
}

var make = Button;

export {
  make ,
  
}
/*  Not a pure module */
