// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./Button.bs.js";
import * as Render from "../../lib/Render.bs.js";
import * as Helpers from "../../lib/Helpers.bs.js";
import * as React$1 from "@storybook/react";

React$1.storiesOf("Button", Helpers.storybookModule).add("Basic usage", (function (param) {
          return React.createElement(Button.make, {
                      children: Render.s("Click here")
                    });
        })).add("Block prop", (function (param) {
        return React.createElement(Button.make, {
                    children: Render.s("Click here"),
                    block: true
                  });
      }));

export {
  
}
/*  Not a pure module */
