// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "../../lib/Theme.bs.js";
import * as React from "react";
import * as Css from "@emotion/css";

function button(block) {
  return Css.css({
              background: Theme.Colors.blue,
              border: 0,
              color: Theme.Colors.white,
              minWidth: block ? "100%" : "20rem",
              height: "5.5rem",
              borderRadius: Theme.Radius.small,
              cursor: "pointer",
              fontFamily: Theme.fontFamily,
              fontSize: "2.0rem"
            });
}

function Button(Props) {
  var children = Props.children;
  var blockOpt = Props.block;
  var onClick = Props.onClick;
  var block = blockOpt !== undefined ? blockOpt : false;
  return React.createElement("button", {
              className: button(block),
              onClick: onClick
            }, children);
}

var make = Button;

export {
  button ,
  make ,
  
}
/* react Not a pure module */
