// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Helpers from "../../lib/Helpers.bs.js";
import * as React$1 from "@storybook/react";

React$1.storiesOf("Tab", Helpers.storybookModule).add("Basic usage", (function (param) {
        return React.createElement("div", undefined);
      }));

export {
  
}
/*  Not a pure module */
