// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../Card/Card.bs.js";
import * as Tabs from "./Tabs.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Render from "../../lib/helpers/Render.bs.js";
import * as Helpers from "../../lib/helpers/Helpers.bs.js";
import * as Typography from "../Typography/Typography.bs.js";
import * as React$1 from "@storybook/react";

React$1.storiesOf("Tabs", Helpers.storybookModule).add("Basic usage", (function (param) {
        var match = React.useState(function () {
              return 0;
            });
        var setTab = match[1];
        var tab = match[0];
        var tabs = [
          {
            label: "Global feed",
            id: 0
          },
          {
            label: "Your feed",
            id: 1
          }
        ];
        return React.createElement("div", undefined, React.createElement(Tabs.make, {
                        tabs: tabs,
                        onChange: (function (id) {
                            return Curry._1(setTab, (function (param) {
                                          return id;
                                        }));
                          }),
                        current: tab
                      }), React.createElement("br", undefined), React.createElement("div", undefined, React.createElement(Tabs.Panel.make, {
                            active: tab === 0,
                            children: React.createElement(Card.make, {
                                  children: React.createElement(Typography.make, {
                                        variant: "title",
                                        level: 2,
                                        children: Render.s("The global feed...")
                                      })
                                })
                          }), React.createElement(Tabs.Panel.make, {
                            active: tab === 1,
                            children: React.createElement(Card.make, {
                                  children: null
                                }, React.createElement(Typography.make, {
                                      variant: "title",
                                      level: 1,
                                      children: Render.s("ReScript & React.js - Real World App")
                                    }), React.createElement(Typography.make, {
                                      children: Render.s("Texto")
                                    }))
                          })));
      }));

export {
  
}
/*  Not a pure module */
