// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Theme from "../../lib/Theme.bs.js";

var tabs = CssJs.style([
      CssJs.display("flex"),
      CssJs.margin(CssJs.zero),
      CssJs.padding(CssJs.zero)
    ]);

function tab(active) {
  return CssJs.style([
              CssJs.listStyleType(CssJs.none),
              CssJs.selector("> button", [
                    CssJs.transition(200, undefined, undefined, "color"),
                    CssJs.padding2(Theme.Spacing.make(1), Theme.Spacing.make(2)),
                    CssJs.borderRadius(Theme.Radius.small),
                    CssJs.background(active ? Theme.Colors.blueGradient : CssJs.transparent),
                    CssJs.color(active ? CssJs.hex(Theme.Colors.white) : CssJs.hex(Theme.Colors.gray1)),
                    CssJs.borderStyle(CssJs.none),
                    CssJs.fontFamily(Theme.fontFamily),
                    CssJs.cursor(CssJs.pointer)
                  ]),
              CssJs.hover([CssJs.selector("> button", [
                          CssJs.transition(200, undefined, undefined, "color"),
                          CssJs.color(active ? CssJs.hex(Theme.Colors.white) : CssJs.hex(Theme.Colors.blue))
                        ])])
            ]);
}

export {
  tabs ,
  tab ,
  
}
/* tabs Not a pure module */
