// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "../../lib/Theme.bs.js";
import * as Css from "@emotion/css";

var tabs = Css.css({
      display: "flex",
      margin: 0,
      padding: 0
    });

function tab(active) {
  return Css.css({
              listStyle: "none",
              "> button": {
                transition: "200ms color",
                padding: Theme.Spacing.make(1) + " " + Theme.Spacing.make(2),
                borderRadius: Theme.Radius.small,
                background: active ? Theme.Colors.blueGradient : "transparent",
                color: active ? Theme.Colors.white : Theme.Colors.gray1,
                border: "none",
                fontFamily: Theme.fontFamily,
                cursor: "pointer"
              },
              "&:hover": {
                "> button": {
                  transition: "200ms color",
                  color: active ? Theme.Colors.white : Theme.Colors.blue
                }
              }
            });
}

export {
  tabs ,
  tab ,
  
}
/* tabs Not a pure module */
