// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "../Theme.bs.js";

var stringifySpacing = Theme.Spacing.make;

var empty = {
  xxs: undefined,
  xs: undefined,
  sm: undefined,
  md: undefined,
  lg: undefined,
  xl: undefined
};

export {
  empty ,
  stringifySpacing ,
  
}
/* No side effect */
