@module("@emotion/css") external css: {..} => string = "css"
@module("@emotion/css") external raw: string => string = "css"
@module("@emotion/css") external keyframes: {..} => string = "keyframes"
@module("@emotion/css") external cx: array<string> => string = "cx"
@module("@emotion/css") external injectGlobal: string => unit = "injectGlobal"
