// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@emotion/css";

function includeStyles(param) {
  Css.injectGlobal("\n  html, body, #root {\n    height: 100%;\n    width: 100%;\n    padding: 0;\n    margin: 0;\n  }\n\n  html {\n    font-size: 10px;\n  }\n\n  * {\n    box-sizing: border-box;\n  }\n");
  
}

export {
  includeStyles ,
  
}
/* @emotion/css Not a pure module */
