// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "../../lib/theme/Theme.bs.js";
import * as React from "react";
import * as Css from "@emotion/css";

var h1 = Css.css({
      fontSize: "3.2rem",
      fontFamily: Theme.fontFamily,
      fontWeight: "bold",
      color: Theme.Colors.black,
      margin: 0,
      marginBottom: Theme.Spacing.make(3)
    });

var h2 = Css.css({
      fontSize: "2.8rem",
      fontFamily: Theme.fontFamily,
      fontWeight: "bold",
      color: Theme.Colors.black,
      margin: 0,
      marginBottom: Theme.Spacing.make(3)
    });

var text = Css.css({
      fontSize: "2.0rem",
      fontFamily: Theme.fontFamily,
      letterSpacing: "-0.02em",
      color: Theme.Colors.gray1,
      margin: 0,
      marginBottom: Theme.Spacing.make(2)
    });

function Typography(Props) {
  var variantOpt = Props.variant;
  var levelOpt = Props.level;
  var children = Props.children;
  var variant = variantOpt !== undefined ? variantOpt : "text";
  var level = levelOpt !== undefined ? levelOpt : 1;
  if (variant === "title") {
    if (level === 2) {
      return React.createElement("h2", {
                  className: h2
                }, children);
    } else {
      return React.createElement("h1", {
                  className: h1
                }, children);
    }
  } else {
    return React.createElement("p", {
                className: text
              }, children);
  }
}

var make = Typography;

export {
  h1 ,
  h2 ,
  text ,
  make ,
  
}
/* h1 Not a pure module */
