// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Render from "../../lib/Render.bs.js";
import * as Helpers from "../../lib/Helpers.bs.js";
import * as Typography from "./Typography.bs.js";
import * as React$1 from "@storybook/react";

React$1.storiesOf("Typography", Helpers.storybookModule).add("Basic usage", (function (param) {
            return React.createElement(Typography.make, {
                        children: Render.s("Don’t have an account?")
                      });
          })).add("Title 1", (function (param) {
          return React.createElement(Typography.make, {
                      variant: "title",
                      level: "h1",
                      children: Render.s("Title 1")
                    });
        })).add("Title 2", (function (param) {
        return React.createElement(Typography.make, {
                    variant: "title",
                    level: "h2",
                    children: Render.s("Title 2")
                  });
      }));

export {
  
}
/*  Not a pure module */
