// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "../../lib/theme/Theme.bs.js";
import * as React from "react";
import * as Css from "@emotion/css";

var card = Css.css({
      background: Theme.Colors.lightBlue1,
      borderRadius: Theme.Radius.medium,
      padding: "3.2rem"
    });

function Card(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: card
            }, children);
}

var make = Card;

export {
  card ,
  make ,
  
}
/* card Not a pure module */
