// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Theme from "../../lib/Theme.bs.js";
import * as React from "react";

var card = CssJs.style([
      CssJs.background(CssJs.hex(Theme.Colors.lightBlue1)),
      CssJs.borderRadius(Theme.Radius.small)
    ]);

function Card(Props) {
  return React.createElement("div", undefined);
}

var make = Card;

export {
  card ,
  make ,
  
}
/* card Not a pure module */
