// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "./Card.bs.js";
import * as React from "react";
import * as Render from "../../lib/Render.bs.js";
import * as Helpers from "../../lib/Helpers.bs.js";
import * as Typography from "../Typography/Typography.bs.js";
import * as React$1 from "@storybook/react";

React$1.storiesOf("Card", Helpers.storybookModule).add("Basic usage", (function (param) {
        return React.createElement(Card.make, {
                    children: null
                  }, React.createElement(Typography.make, {
                        variant: "title",
                        level: 1,
                        children: Render.s("ReScript & React.js - Real World App")
                      }), React.createElement(Typography.make, {
                        children: Render.s("Texto")
                      }));
      }));

export {
  
}
/*  Not a pure module */
