// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Signin(Props) {
  return React.createElement("div", undefined);
}

var make = Signin;

export {
  make ,
  
}
/* react Not a pure module */
