// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UI from "../../lib/ui/UI.bs.js";
import * as Link from "../../components/Link/Link.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Input from "../../components/Input/Input.bs.js";
import * as Theme from "../../lib/theme/Theme.bs.js";
import * as React from "react";
import * as Button from "../../components/Button/Button.bs.js";
import * as Render from "../../lib/helpers/Render.bs.js";
import * as UIBase from "../../lib/ui/UIBase.bs.js";
import * as UIFlex from "../../lib/ui/UIFlex.bs.js";
import * as Devices from "../../lib/helpers/Devices.bs.js";
import * as Typography from "../../components/Typography/Typography.bs.js";
import * as Css from "@emotion/css";

var wrapper = Css.css("\n  background: " + Theme.Colors.blue + ";\n");

var formWrapper = Css.css(Devices.Raw.md("\n  max-width: 100%;\n  ")("\n    max-width: 40.0rem;\n  "));

function Signin(Props) {
  return React.createElement(UIFlex.make, Curry._3(UIFlex.makeProps(undefined)(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, UI.all({
                          NAME: "pct",
                          VAL: 100.0
                        }), undefined, undefined, undefined, undefined, undefined, null), undefined, undefined, undefined), React.createElement(UIBase.make, {
                  display: [
                    UI.xxs("none"),
                    UI.md("block")
                  ],
                  p: UI.all(6),
                  xxs: 6,
                  children: Render.s("Box"),
                  className: wrapper
                }), React.createElement(UIBase.make, {
                  display: UI.all("flex"),
                  justifyContent: UI.all("center"),
                  alignItems: UI.all("center"),
                  xxs: 12,
                  md: 6,
                  children: React.createElement(UIBase.make, {
                        display: UI.all("flex"),
                        flexDirection: UI.all("column"),
                        children: null,
                        className: formWrapper
                      }, React.createElement(Typography.make, {
                            variant: "title",
                            level: 1,
                            children: Render.s("Sign in")
                          }), React.createElement(Typography.make, {
                            variant: "text",
                            level: 1,
                            children: null
                          }, Render.s("Don't have an account? "), React.createElement(Link.make, {
                                children: Render.s("Sign in")
                              })), React.createElement(UIBase.make, {
                            mt: UI.all(6),
                            mb: UI.all(4),
                            children: React.createElement(Input.make, {
                                  placeholder: "Email"
                                })
                          }), React.createElement(UIBase.make, {
                            mb: UI.all(4),
                            children: React.createElement(Input.make, {
                                  placeholder: "Password"
                                })
                          }), React.createElement(Button.make, {
                            children: Render.s("Sign in"),
                            block: true
                          }), React.createElement(UIBase.make, {
                            mt: UI.all(6),
                            children: React.createElement(Typography.make, {
                                  variant: "text",
                                  children: null
                                }, Render.s("Skip sign-in for now and "), React.createElement(Link.make, {
                                      children: Render.s("start reading")
                                    }))
                          }))
                }));
}

var make = Signin;

export {
  wrapper ,
  formWrapper ,
  make ,
  
}
/* wrapper Not a pure module */
