// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UICore from "./UICore.bs.js";

var all = UICore.all;

var xxs = UICore.xxs;

var xs = UICore.xs;

var sm = UICore.sm;

var md = UICore.md;

var lg = UICore.lg;

var xl = UICore.xl;

var makeStyles = UICore.makeStyles;

var Basem;

var Box;

var Flex;

export {
  all ,
  xxs ,
  xs ,
  sm ,
  md ,
  lg ,
  xl ,
  makeStyles ,
  Basem ,
  Box ,
  Flex ,
  
}
/* UICore Not a pure module */
