// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UIResponsive from "./UIResponsive.bs.js";

function all(v) {
  return [{
            NAME: "xxs",
            VAL: v
          }];
}

function xxs(v) {
  return {
          NAME: "xxs",
          VAL: v
        };
}

function xs(v) {
  return {
          NAME: "xs",
          VAL: v
        };
}

function sm(v) {
  return {
          NAME: "sm",
          VAL: v
        };
}

function md(v) {
  return {
          NAME: "md",
          VAL: v
        };
}

function lg(v) {
  return {
          NAME: "lg",
          VAL: v
        };
}

function xl(v) {
  return {
          NAME: "xl",
          VAL: v
        };
}

var makeStyles = UIResponsive.make;

export {
  all ,
  xxs ,
  xs ,
  sm ,
  md ,
  lg ,
  xl ,
  makeStyles ,
  
}
/* UIResponsive Not a pure module */
