// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as UIBase from "./UIBase.bs.js";
import * as UICore from "./UICore.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Css from "@emotion/css";

var flex = Css.css("\n  width: 100%;\n  flex-wrap: wrap;\n");

function makeProps(customClassOpt) {
  var customClass = customClassOpt !== undefined ? customClassOpt : "";
  var arg = flex + " " + customClass;
  return function (param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18, param$19, param$20, param$21, param$22, param$23, param$24, param$25, param$26, param$27, param$28, param$29, param$30) {
    var partial_arg = [UICore.xxs("flex")];
    var func = function (param$31, param$32, param$33, param$34) {
      var tmp = {
        children: param$30
      };
      if (partial_arg !== undefined) {
        tmp.display = Caml_option.valFromOption(partial_arg);
      }
      if (param !== undefined) {
        tmp.justifyContent = Caml_option.valFromOption(param);
      }
      if (param$1 !== undefined) {
        tmp.flexDirection = Caml_option.valFromOption(param$1);
      }
      if (param$2 !== undefined) {
        tmp.alignItems = Caml_option.valFromOption(param$2);
      }
      if (param$3 !== undefined) {
        tmp.p = Caml_option.valFromOption(param$3);
      }
      if (param$4 !== undefined) {
        tmp.px = Caml_option.valFromOption(param$4);
      }
      if (param$5 !== undefined) {
        tmp.py = Caml_option.valFromOption(param$5);
      }
      if (param$6 !== undefined) {
        tmp.pt = Caml_option.valFromOption(param$6);
      }
      if (param$7 !== undefined) {
        tmp.pb = Caml_option.valFromOption(param$7);
      }
      if (param$8 !== undefined) {
        tmp.pl = Caml_option.valFromOption(param$8);
      }
      if (param$9 !== undefined) {
        tmp.pr = Caml_option.valFromOption(param$9);
      }
      if (param$10 !== undefined) {
        tmp.m = Caml_option.valFromOption(param$10);
      }
      if (param$11 !== undefined) {
        tmp.mx = Caml_option.valFromOption(param$11);
      }
      if (param$12 !== undefined) {
        tmp.my = Caml_option.valFromOption(param$12);
      }
      if (param$13 !== undefined) {
        tmp.mt = Caml_option.valFromOption(param$13);
      }
      if (param$14 !== undefined) {
        tmp.mb = Caml_option.valFromOption(param$14);
      }
      if (param$15 !== undefined) {
        tmp.ml = Caml_option.valFromOption(param$15);
      }
      if (param$16 !== undefined) {
        tmp.mr = Caml_option.valFromOption(param$16);
      }
      if (param$17 !== undefined) {
        tmp.xxs = Caml_option.valFromOption(param$17);
      }
      if (param$18 !== undefined) {
        tmp.xs = Caml_option.valFromOption(param$18);
      }
      if (param$19 !== undefined) {
        tmp.sm = Caml_option.valFromOption(param$19);
      }
      if (param$20 !== undefined) {
        tmp.md = Caml_option.valFromOption(param$20);
      }
      if (param$21 !== undefined) {
        tmp.lg = Caml_option.valFromOption(param$21);
      }
      if (param$22 !== undefined) {
        tmp.xl = Caml_option.valFromOption(param$22);
      }
      if (param$23 !== undefined) {
        tmp.width = Caml_option.valFromOption(param$23);
      }
      if (param$24 !== undefined) {
        tmp.height = Caml_option.valFromOption(param$24);
      }
      if (param$25 !== undefined) {
        tmp.position = Caml_option.valFromOption(param$25);
      }
      if (param$26 !== undefined) {
        tmp.top = Caml_option.valFromOption(param$26);
      }
      if (param$27 !== undefined) {
        tmp.bottom = Caml_option.valFromOption(param$27);
      }
      if (param$28 !== undefined) {
        tmp.left = Caml_option.valFromOption(param$28);
      }
      if (param$29 !== undefined) {
        tmp.right = Caml_option.valFromOption(param$29);
      }
      if (param$31 !== undefined) {
        tmp.tag = Caml_option.valFromOption(param$31);
      }
      if (param$32 !== undefined) {
        tmp.className = Caml_option.valFromOption(param$32);
      }
      if (param$33 !== undefined) {
        tmp.key = param$33;
      }
      return tmp;
    };
    return function (param) {
      return Curry._2(func, param, arg);
    };
  };
}

var make = UIBase.make;

export {
  flex ,
  make ,
  makeProps ,
  
}
/* flex Not a pure module */
