// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "../theme/Theme.bs.js";

var stringifySpacing = Theme.Spacing.make;

function stringifySize(size) {
  var variant = size.NAME;
  if (variant === "px") {
    return size.VAL.toString() + "px";
  } else if (variant === "pct") {
    return size.VAL.toString() + "%";
  } else if (variant === "rem") {
    return size.VAL.toString() + "rem";
  } else {
    return size.VAL.toString() + "rem";
  }
}

var empty = {
  xxs: undefined,
  xs: undefined,
  sm: undefined,
  md: undefined,
  lg: undefined,
  xl: undefined
};

export {
  empty ,
  stringifySpacing ,
  stringifySize ,
  
}
/* No side effect */
