// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Render from "../../lib/Render.bs.js";
import * as Tab_Styles from "./Tab_Styles.bs.js";
import * as Typography from "../Typography/Typography.bs.js";

function Tab(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: Tab_Styles.tab
            }, children);
}

function Tab$Pane(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: Tab_Styles.pane
            }, React.createElement(Typography.make, {
                  children: Render.s("Title")
                }), children);
}

var Pane = {
  make: Tab$Pane
};

function Tab$Content(Props) {
  var children = Props.children;
  return React.createElement("div", undefined, children);
}

var Content = {
  make: Tab$Content
};

var Styles;

var make = Tab;

export {
  Styles ,
  make ,
  Pane ,
  Content ,
  
}
/* react Not a pure module */
