// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tab from "./Tab.bs.js";
import * as React from "react";
import * as Render from "../../lib/Render.bs.js";
import * as Helpers from "../../lib/Helpers.bs.js";
import * as React$1 from "@storybook/react";

React$1.storiesOf("Tab", Helpers.storybookModule).add("Basic usage", (function (param) {
        return React.createElement(Tab.make, {
                    children: null
                  }, React.createElement(Tab.Pane.make, {
                        children: Render.s("Tab content for your feed")
                      }), React.createElement(Tab.Pane.make, {
                        children: Render.s("Tab content for global feed")
                      }));
      }));

export {
  
}
/*  Not a pure module */
