// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";

var tab = CssJs.style([
      CssJs.border(CssJs.px(1), CssJs.solid, CssJs.red),
      CssJs.display("flex")
    ]);

var pane = CssJs.style([CssJs.border(CssJs.px(1), CssJs.solid, CssJs.green)]);

export {
  tab ,
  pane ,
  
}
/* tab Not a pure module */
