// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.bs.js";
import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as React from "react";

function toRem(value) {
  return Css.rem(value * 0.8);
}

function margins(param) {
  return CssJs.margin4(toRem(param[0]), toRem(param[3]), toRem(param[2]), toRem(param[1]));
}

function paddings(param) {
  return CssJs.padding4(toRem(param[0]), toRem(param[3]), toRem(param[2]), toRem(param[1]));
}

function box(direction_, align, justify, block_, fullHeight, marginT, paddingT) {
  return CssJs.style([
              CssJs.display("flex"),
              CssJs.flexDirection(direction_),
              CssJs.alignItems(align),
              CssJs.justifyContent(justify),
              CssJs.width(block_ ? CssJs.pct(100.0) : CssJs.auto),
              CssJs.height(fullHeight ? CssJs.pct(100.0) : CssJs.auto),
              margins(marginT),
              paddings(paddingT)
            ]);
}

function Box(Props) {
  var children = Props.children;
  var directionOpt = Props.direction;
  var alignOpt = Props.align;
  var justifyOpt = Props.justify;
  var blockOpt = Props.block;
  var fullHeightOpt = Props.fullHeight;
  var marginOpt = Props.margin;
  var paddingOpt = Props.padding;
  var direction = directionOpt !== undefined ? directionOpt : "row";
  var align = alignOpt !== undefined ? alignOpt : "center";
  var justify = justifyOpt !== undefined ? justifyOpt : "center";
  var block = blockOpt !== undefined ? blockOpt : true;
  var fullHeight = fullHeightOpt !== undefined ? fullHeightOpt : false;
  var margin = marginOpt !== undefined ? marginOpt : [
      0,
      0,
      0,
      0
    ];
  var padding = paddingOpt !== undefined ? paddingOpt : [
      0,
      0,
      0,
      0
    ];
  return React.createElement("div", {
              className: box(direction, align, justify, block, fullHeight, margin, padding)
            }, children);
}

var Int;

var make = Box;

export {
  Int ,
  toRem ,
  margins ,
  paddings ,
  box ,
  make ,
  
}
/* Css Not a pure module */
