// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Signin from "./pages/Signin/Signin.bs.js";
import * as GlobalStyles from "./lib/helpers/GlobalStyles.bs.js";

GlobalStyles.includeStyles(undefined);

function App(Props) {
  return React.createElement(Signin.make, {});
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
