// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./components/Button/Button.bs.js";

function App(Props) {
  return React.createElement("div", undefined, React.createElement(Button.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
