// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "./Link.bs.js";
import * as React from "react";
import * as Render from "../../lib/helpers/Render.bs.js";
import * as Helpers from "../../lib/helpers/Helpers.bs.js";
import * as React$1 from "@storybook/react";

React$1.storiesOf("Link", Helpers.storybookModule).add("Basic usage", (function (param) {
        return React.createElement(Link.make, {
                    children: Render.s("Sign up")
                  });
      }));

export {
  
}
/*  Not a pure module */
